// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfmwlswaadgrqtrweezu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmbXdsc3dhYWRncnF0cndlZXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjI3NDEsImV4cCI6MjA2MDg5ODc0MX0.h9-mvJC3wEdgojwgZKVYF43twFFJm0Mr5XC2iIUCzqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);